In [1]:
import pandas as pd
import numpy as np

#By default, pandas doesn't show all of the columns, instead it only shows the first few and the last few. but this pandas display setting is telling pandas to display all the column
#pandas has many display setting that control how data is shown, adding the "None", tell the pandas to display all 
# Display all columns
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv(r"C:\Users\User\Desktop\DATA ANALYSIS PROJECTS\EXCEL DATASETS\WA_Fn-UseC_-Telco-Customer-Churn.csv")
#df = df.replace(" ", np.nan) #replaces all blank space to NaN

In [3]:
df.shape

(7043, 21)

In [4]:
#understanding the dataset, Number of rows, Number of columns, Data types, Missing values
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [5]:
#generates a statistical summary of the DataFrame, to know if there is any missing data
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [6]:
#df.duplicate() returns boolean series indicating if there is a duplicate in the role. sum() counts the total number of duplicate
#if duplicate exist, df.drop_duplicates() to remove the dupliicate
df.duplicated().sum()

np.int64(0)

In [7]:
#to check if there are any null value in the column in the dataframe df.isnull() 
# .sum() counts the number of null values by turning the bolean True/False into 1 and 0 and counting 
#if there are any null values, you know which columns need attention before analysis
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [8]:
# (df == " ") finds the blanK Space as a boolean and the .sum() counts the the boolean True and False into 1 and 0 to know the number of blank space 
(df == " ").sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [9]:
#df['TotalCharge'] Selects the TotalCharges column.  
#.replace(old value, new value)
# .replace(' ', np.nan)
df['TotalCharges'] = df['TotalCharges'].replace(' ', np.nan)

In [10]:
#now pandas recongize it a missing value NaN instead of blank 
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [11]:
#check the datatype
df['TotalCharges'].dtype

In [12]:
#the pd.to_numeric() function to convert the datatype of that column into integer or float since we already know its a float
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'])

In [13]:
#Verifiy the the Totalcharge has now been converted numerical value 
df['TotalCharges'].dtypes

dtype('float64')

In [14]:
#use .dropna() to drop or remove any row/column with NaN, since its just 11 missing value, its really insignificant
#(inplace = True) modifies the dataframe, instead of creating a new dataframe 
df.dropna(inplace=True)
#verifiy again that rows/columns with NaN values have been removed 
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [15]:
#Recheck for Duplicates again
df.duplicated().sum()

np.int64(0)

In [16]:
#create a loop that iterate through each columns and check the unique values
#for column in the dataframe columns, iterate and print the each unique values in the each columns in the dataframe
for column in df.columns:
    print(column)
    print(df[column].unique())
    print("-----------------")

customerID
<StringArray>
['7590-VHVEG', '5575-GNVDE', '3668-QPYBK', '7795-CFOCW', '9237-HQITU',
 '9305-CDSKC', '1452-KIOVK', '6713-OKOMC', '7892-POOKP', '6388-TABGU',
 ...
 '9767-FFLEM', '0639-TSIQW', '8456-QDAVC', '7750-EYXWZ', '2569-WGERO',
 '6840-RESVB', '2234-XADUH', '4801-JZAZL', '8361-LTMKD', '3186-AJIEK']
Length: 7032, dtype: str
-----------------
gender
<StringArray>
['Female', 'Male']
Length: 2, dtype: str
-----------------
SeniorCitizen
[0 1]
-----------------
Partner
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
-----------------
Dependents
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
-----------------
tenure
[ 1 34  2 45  8 22 10 28 62 13 16 58 49 25 69 52 71 21 12 30 47 72 17 27
  5 46 11 70 63 43 15 60 18 66  9  3 31 50 64 56  7 42 35 48 29 65 38 68
 32 55 37 36 41  6  4 33 67 23 57 61 14 20 53 40 59 24 44 19 54 51 26 39]
-----------------
PhoneService
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
-----------------
MultipleLines
<StringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str
-----------------
InternetService
<StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str
-----------------
OnlineSecurity
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
-----------------
OnlineBackup
<StringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str
-----------------
DeviceProtection
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
-----------------
TechSupport
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
-----------------
StreamingTV
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
-----------------
StreamingMovies
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
-----------------
Contract
<StringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str
-----------------
PaperlessBilling
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
-----------------
PaymentMethod
<StringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str
-----------------
MonthlyCharges
[29.85 56.95 53.85 ... 63.1  44.2  78.7 ]
-----------------
TotalCharges
[  29.85 1889.5   108.15 ...  346.45  306.6  6844.5 ]
-----------------
Churn
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
-----------------

In [17]:

df.select_dtypes(include="object").describe()

C:\Users\User\AppData\Local\Temp\ipykernel_14908\1543874215.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object").describe()

,customerID,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Churn
count,7032,7032,7032,7032,7032,7032,7032,7032,7032,7032,7032,7032,7032,7032,7032,7032,7032
unique,7032,2,2,2,2,3,3,3,3,3,3,3,3,3,2,4,2
top,7590-VHVEG,Male,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,No
freq,1,3549,3639,4933,6352,3385,3096,3497,3087,3094,3472,2809,2781,3875,4168,2365,5163

In [18]:
#drop the irrelevant column because the customer ID is just an identifier and not useful 
df.drop("customerID", axis=1, inplace=True)

In [19]:
#reverify the datatypes again to make sure numerical columns are int or float and categorical columns are objects 
df.info()

<class 'pandas.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7032 non-null   str
 1   SeniorCitizen     7032 non-null   int64
 2   Partner           7032 non-null   str
 3   Dependents        7032 non-null   str
 4   tenure            7032 non-null   int64
 5   PhoneService      7032 non-null   str
 6   MultipleLines     7032 non-null   str
 7   InternetService   7032 non-null   str
 8   OnlineSecurity    7032 non-null   str
 9   OnlineBackup      7032 non-null   str
 10  DeviceProtection  7032 non-null   str
 11  TechSupport       7032 non-null   str
 12  StreamingTV       7032 non-null   str
 13  StreamingMovies   7032 non-null   str
 14  Contract          7032 non-null   str
 15  PaperlessBilling  7032 non-null   str
 16  PaymentMethod     7032 non-null   str
 17  MonthlyCharges    7032 non-null   float64
 18  TotalCharges      7032 non-null   float64
 19  Churn             7032 non-null   str
dtypes: float64(2), int64(2), str(16)
memory usage: 1.1 MB

In [20]:
df.to_csv("Telco_Customer_Churn_Cleaned.csv", index=False)